<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TemplateProject.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudL.Core" />
    <PackageReference Include="CloudL.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TemplateProject.Application.Contracts\TemplateProject.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
