<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TemplateProject.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Livia.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TemplateProject.Domain.Shared\TemplateProject.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
