<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CloudL.IntegrationTests</AssemblyName>
    <RootNamespace>CloudL.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CloudL.AspNetCore\CloudL.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\CloudL.Core\CloudL.Core.csproj" />
    <ProjectReference Include="..\..\src\CloudL.EntityFrameworkCore\CloudL.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
