<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TemplateProject.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudL.Core" />
    <PackageReference Include="Mapster" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TemplateProject.Domain\TemplateProject.Domain.csproj" />
    <ProjectReference Include="..\TemplateProject.Application.Contracts\TemplateProject.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
